/** Static problem title lookup — safe to import in client components (no `fs`). */
export const PROBLEM_TITLES: Record<string, string> = {
  '000': 'Factorial',
  '001': 'Two Sum',
  '002': 'Add Two Numbers',
  '003': 'Longest Substring Without Repeating Characters',
  '004': 'Median of Two Sorted Arrays',
  '005': 'Longest Palindromic Substring',
  '007': 'Reverse Integer',
  '010': 'Regular Expression Matching',
  '011': 'Container With Most Water',
  '015': '3Sum',
  '017': 'Letter Combinations of a Phone Number',
  '019': 'Remove Nth Node From End of List',
  '020': 'Valid Parentheses',
  '021': 'Merge Two Sorted Lists',
  '022': 'Generate Parentheses',
  '023': 'Merge K Sorted Lists',
  '025': 'Reverse Nodes in K-Group',
  '026': 'Remove Duplicates from Sorted Array',
  '027': 'Remove Element',
  '032': 'Longest Valid Parentheses',
  '033': 'Search in Rotated Sorted Array',
  '034': 'Find First and Last Position of Element in Sorted Array',
  '035': 'Search Insert Position',
  '036': 'Valid Sudoku',
  '037': 'Sudoku Solver',
  '039': 'Combination Sum',
  '040': 'Combination Sum II',
  '042': 'Trapping Rain Water',
  '043': 'Multiply Strings',
  '045': 'Jump Game II',
  '046': 'Permutations',
  '048': 'Rotate Image',
  '049': 'Group Anagrams',
  '050': 'Pow(x, n)',
  '051': 'N-Queens',
  '053': 'Maximum Subarray',
  '054': 'Spiral Matrix',
  '055': 'Jump Game',
  '056': 'Merge Intervals',
  '057': 'Insert Interval',
  '062': 'Unique Paths',
  '066': 'Plus One',
  '069': 'Sqrt(x)',
  '070': 'Climbing Stairs',
  '072': 'Edit Distance',
  '073': 'Set Matrix Zeroes',
  '074': 'Search a 2D Matrix',
  '075': 'Sort Colors',
  '076': 'Minimum Window Substring',
  '077': 'Combinations',
  '078': 'Subsets',
  '079': 'Word Search',
  '084': 'Largest Rectangle in Histogram',
  '088': 'Merge Sorted Array',
  '090': 'Subsets II',
  '091': 'Decode Ways',
  '092': 'Reverse Linked List II',
  '097': 'Interleaving String',
  '098': 'Validate Binary Search Tree',
  '100': 'Same Tree',
  '102': 'Binary Tree Level Order Traversal',
  '104': 'Maximum Depth of Binary Tree',
  '105': 'Construct Binary Tree from Preorder and Inorder Traversal',
  '110': 'Balanced Binary Tree',
  '114': 'Flatten Binary Tree to Linked List',
  '115': 'Distinct Subsequences',
  '121': 'Best Time to Buy and Sell Stock',
  '124': 'Binary Tree Maximum Path Sum',
  '125': 'Valid Palindrome',
  '127': 'Word Ladder',
  '128': 'Longest Consecutive Sequence',
  '130': 'Surrounded Regions',
  '131': 'Palindrome Partitioning',
  '133': 'Clone Graph',
  '134': 'Gas Station',
  '136': 'Single Number',
  '138': 'Copy List with Random Pointer',
  '139': 'Word Break',
  '141': 'Linked List Cycle',
  '143': 'Reorder List',
  '144': 'Binary Tree Preorder Traversal',
  '146': 'LRU Cache',
  '150': 'Evaluate Reverse Polish Notation',
  '152': 'Maximum Product Subarray',
  '153': 'Find Minimum in Rotated Sorted Array',
  '155': 'Min Stack',
  '162': 'Find Peak Element',
  '167': 'Two Sum II - Input Array Is Sorted',
  '190': 'Reverse Bits',
  '191': 'Number of 1 Bits',
  '198': 'House Robber',
  '199': 'Binary Tree Right Side View',
  '200': 'Number of Islands',
  '202': 'Happy Number',
  '206': 'Reverse Linked List',
  '207': 'Course Schedule',
  '208': 'Implement Trie (Prefix Tree)',
  '210': 'Course Schedule II',
  '211': 'Design Add and Search Words Data Structure',
  '212': 'Word Search II',
  '213': 'House Robber II',
  '215': 'Kth Largest Element in an Array',
  '217': 'Contains Duplicate',
  '226': 'Invert Binary Tree',
  '230': 'Kth Smallest Element in a BST',
  '232': 'Implement Queue using Stacks',
  '235': 'Lowest Common Ancestor of a Binary Search Tree',
  '236': 'Lowest Common Ancestor of a Binary Tree',
  '238': 'Product of Array Except Self',
  '239': 'Sliding Window Maximum',
  '242': 'Valid Anagram',
  '252': 'Meeting Rooms',
  '253': 'Meeting Rooms II',
  '261': 'Graph Valid Tree',
  '268': 'Missing Number',
  '269': 'Alien Dictionary',
  '271': 'Encode and Decode Strings',
  '278': 'First Bad Version',
  '286': 'Walls and Gates',
  '287': 'Find the Duplicate Number',
  '295': 'Find Median from Data Stream',
  '297': 'Serialize and Deserialize Binary Tree',
  '300': 'Longest Increasing Subsequence',
  '309': 'Best Time to Buy and Sell Stock with Cooldown',
  '312': 'Burst Balloons',
  '322': 'Coin Change',
  '323': 'Number of Connected Components in an Undirected Graph',
  '329': 'Longest Increasing Path in a Matrix',
  '332': 'Reconstruct Itinerary',
  '338': 'Counting Bits',
  '344': 'Reverse String',
  '347': 'Top K Frequent Elements',
  '355': 'Design Twitter',
  '371': 'Sum of Two Integers',
  '374': 'Guess Number Higher or Lower',
  '387': 'First Unique Character in a String',
  '394': 'Decode String',
  '402': 'Remove K Digits',
  '416': 'Partition Equal Subset Sum',
  '417': 'Pacific Atlantic Water Flow',
  '424': 'Longest Repeating Character Replacement',
  '435': 'Non-overlapping Intervals',
  '494': 'Target Sum',
  '509': 'Fibonacci Number',
  '518': 'Coin Change II',
  '543': 'Diameter of Binary Tree',
  '547': 'Number of Provinces',
  '560': 'Subarray Sum Equals K',
  '567': 'Permutation in String',
  '572': 'Subtree of Another Tree',
  '621': 'Task Scheduler',
  '643': 'Maximum Average Subarray I',
  '647': 'Palindromic Substrings',
  '678': 'Valid Parenthesis String',
  '684': 'Redundant Connection',
  '695': 'Max Area of Island',
  '701': 'Insert into a Binary Search Tree',
  '703': 'Kth Largest Element in a Stream',
  '704': 'Binary Search',
  '739': 'Daily Temperatures',
  '743': 'Network Delay Time',
  '746': 'Min Cost Climbing Stairs',
  '763': 'Partition Labels',
  '778': 'Swim in Rising Water',
  '787': 'Cheapest Flights Within K Stops',
  '797': 'All Paths From Source to Target',
  '846': 'Hand of Straights',
  '853': 'Car Fleet',
  '875': 'Koko Eating Bananas',
  '926': 'Flip String to Monotone Increasing',
  '973': 'K Closest Points to Origin',
  '981': 'Time Based Key-Value Store',
  '994': 'Rotting Oranges',
  '1046': 'Last Stone Weight',
  '1091': 'Shortest Path in Binary Matrix',
  '1143': 'Longest Common Subsequence',
  '1448': 'Count Good Nodes in Binary Tree',
  '1584': 'Min Cost to Connect All Points',
  '1851': 'Minimum Interval to Include Each Query',
  '1899': 'Merge Triplets to Form Target Triplet',
  '2013': 'Detect Squares',
};
